#!/bin/bash
set -e
set -x

if [ -z "$GIT_URL" ] ; then
  GIT_URL="https://github.com/michaelsevilla/ceph.git"
fi

if [ -n "$SHA1_OR_REF" ] ; then
  if [ ! -d /ceph/.git ] ; then
    cd /
    git clone $GIT_URL
  fi
  cd /ceph
  git clean -fd
  git checkout master
  if [ `git branch --list dev` ] ; then
    git branch -D dev
  fi
  git checkout -b dev $SHA1_OR_REF
  git clean -fd
  git submodule update --init --recursive
fi

# build source code if /ceph folder exists
if [ "$(ls -A /ceph)" ] ; then
  cd /ceph

  ./autogen.sh
  ./configure \
    --disable-static --with-debug --with-mantle \
    CC='ccache gcc' CFLAGS="-Wall -g" \
    CXX='ccache g++' CXXFLAGS="-Wall -g" \
    LUA_LIBS="-llua5.2" \
    $CEPH_PKGS

  if [ -z $BUILD_THREADS ] ; then
    BUILD_THREADS=4
  fi

  make -j$BUILD_THREADS
  if [ ! -z "$PKG_ARGS" ]; then
    rm -r /ceph/debian || true
    cp -r /debian /ceph/debian
    dpkg-buildpackage -j$BUILD_THREADS $PKG_ARGS
    cp ../ceph-customized*.deb ./
  fi
else
  echo "No /ceph folder found. Either specify a SHA1_OR_REF or put the code there."
  exit 1
fi

exit 0
