#!/bin/bash
set -e


if [ -z "$GIT_URL" ] ; then
  GIT_URL="https://github.com/ceph/ceph"
fi

if [ -n "$SHA1_OR_REF" ] ; then
  if [ ! -d /ceph/.git ] ; then
    cd /
    git clone $GIT_URL
  fi
  cd /ceph
  git clean -fd
  git checkout master
  if [ `git branch --list dev` ] ; then
    git branch -D dev
  fi
  git checkout -b dev $SHA1_OR_REF
  git clean -fd
  git submodule update --init --recursive
  cd src
  git clone --recursive https://github.com/ceph/gmock.git
  cd gmock
  git checkout -b mantle d701f9d547a03677d612d7af3f212871a427f058
fi

# build source code if /ceph folder exists
#if [ "$(ls -A /ceph)" ] ; then
#  cd /ceph
#  ./autogen.sh
#  ./configure \
#    --disable-static --with-debug \
#    CC='ccache gcc' CFLAGS="-Wall -g" \
#    CXX='ccache g++' CXXFLAGS="-Wall -g" \
#    $CEPH_PKGS
#
#  if [ -z $BUILD_THREADS ] ; then
#    BUILD_THREADS=4
#  fi
#
#  exec make -j$BUILD_THREADS
#else
#  echo "No /ceph folder found."
#  exit 1
#fi
#
#exit 0
